# Describes the format for available RainMachine services
disable_program:
  name: Disable Program
  description: Disable a program
  target:
    entity:
      integration: rainmachine
      domain: switch
disable_zone:
  name: Disable Zone
  description: Disable a zone
  target:
    entity:
      integration: rainmachine
      domain: switch
enable_program:
  name: Enable Program
  description: Enable a program
  target:
    entity:
      integration: rainmachine
      domain: switch
enable_zone:
  name: Enable Zone
  description: Enable a zone
  target:
    entity:
      integration: rainmachine
      domain: switch
pause_watering:
  name: Pause All Watering
  description: Pause all watering activities for a number of seconds
  fields:
    device_id:
      name: Controller
      description: The controller whose watering activities should be paused
      required: true
      selector:
        device:
          integration: rainmachine
    seconds:
      name: Duration
      description: The amount of time (in seconds) to pause watering
      required: true
      selector:
        number:
          min: 1
          max: 86400
          unit_of_measurement: seconds
start_program:
  name: Start Program
  description: Start a program
  target:
    entity:
      integration: rainmachine
      domain: switch
start_zone:
  name: Start Zone
  description: Start a zone
  target:
    entity:
      integration: rainmachine
      domain: switch
  fields:
    zone_run_time:
      name: Run Time
      description: The amount of time (in seconds) to run the zone
      default: 600
      selector:
        number:
          min: 1
          max: 86400
          mode: box
stop_all:
  name: Stop All Watering
  description: Stop all watering activities
  fields:
    device_id:
      name: Controller
      description: The controller whose watering activities should be stopped
      required: true
      selector:
        device:
          integration: rainmachine
stop_program:
  name: Stop Program
  description: Stop a program
  target:
    entity:
      integration: rainmachine
      domain: switch
stop_zone:
  name: Stop Zone
  description: Stop a zone
  target:
    entity:
      integration: rainmachine
      domain: switch
unpause_watering:
  name: Unpause All Watering
  description: Unpause all paused watering activities
  fields:
    device_id:
      name: Controller
      description: The controller whose watering activities should be unpaused
      required: true
      selector:
        device:
          integration: rainmachine
